#!/bin/bash

dirty=`git describe --all --dirty | rev | cut -d '-' -f 1 | rev`
if [ "$dirty" = "dirty" ]; then
    echo "This branch is dirty. That would create an ambiguity in what to tag."
    exit 1
fi

if [ -e "pyproject.toml" ]; then
    version_file="pyproject.toml"
elif [ -e "version.py" ]; then
    # If the file with the version declaration is elsewhere, use a symbolic link from version.py to that file
    version_file="version.py"
else
    echo "There is no pyproject.toml or version.py"
    exit 1
fi

version=`grep -i '^version *= *' ${version_file} | sed -E "s/^version *= *['\"]([0-9][^ #'\"]+)['\"].*/\1/gI"`

if [ -z "${version}" ]; then
    echo "pyproject.toml has no 'version = \"...\"' line."
    exit 1
fi
    
new_tag=v${version}

git tag ${new_tag}

if [ $? -ne 0 ]; then
    echo "Adding tag ${new_tag} failed."
    exit 1
else
    echo "Added tag ${new_tag}."
fi

git push origin ${new_tag}

if [ $? -ne 0 ]; then
    echo "Pushing tag ${new_tag} failed."
    exit 1
else
    echo "Pushed tag ${new_tag}."
fi
